[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'ts'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[pluins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = '''
  let g:auto_save = 1
  let g:auto_save_in_insert_mode = 0
'''

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'nnoremap <silent><C-e> :NERDTreeToggle<CR>'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'morhetz/gruvbox'
on_event = ['VimEnter']
hook_add =  '''
  colorscheme gruvbox
  set background=dark
  syntax on
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['gruvbox']
on_source = ['gruvbox']
hook_add = '''
  let g:lightline = {
    \ "colorscheme": "gruvbox"
    \ }
  set laststatus=2
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_guide_size = 1
'''

[[plugins]]
repo = 'gko/vim-coloresque'
