scriptencoding utf-8
set autoread
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8,sjis,cp932
set fileformats=unix,dos,mac
set nobackup
set noswapfile
set noundofile
set viminfo=
set backspace=indent,eol,start