scriptencoding utf-8
set ambiwidth=double
set autoindent
set autoread
set backspace=indent,eol,start
set backup
set cmdheight=1
set cursorcolumn
set cursorline
set encoding=utf-8
set expandtab
set fileencoding=utf-8
set fileencodings=utf-8,sjis,cp932
set fileformats=unix,dos,mac
set hidden
set hlsearch
set ignorecase
set laststatus=2
set list
set listchars=eol:^,nbsp:%,tab:>=,trail:-
set nobackup
set noswapfile
set noundofile
set number
set shiftwidth=2
set showmatch
set showtabline=2
set smartcase
set smartindent
set softtabstop=2
set swapfile
set tabstop=2
set title
set viminfo=
set virtualedit=block
set wildmenu
